### ISSUE TITLE
Limit to the Size of the Message to be Signed

### ISSUE THREAD

**Issue by derknorton** [finwo/supercop#4]
There seems to be a fairly small limit to the size of the message that can be signed.  The following code demonstrates this:
```javascript
const signer = require('supercop');
const seed = signer.createSeed();
const keyPair = await signer.createKeyPair(seed);
for (var size = 100; size < 1300; size++) {
    var bytes = Buffer.alloc(size);
    console.log("Buffer Size: " + size);
    const signature = await signer.sign(bytes, keyPair.publicKey, keyPair.secretKey);
}
```
The resulting output is:
```
        .
        .
        .
Buffer Size: 1215
Buffer Size: 1216
Buffer Size: 1217
Buffer Size: 1218
Buffer Size: 1219
Buffer Size: 1220
Buffer Size: 1221
     RangeError: Invalid typed array length: 1221
      at new Uint8Array (<anonymous>)
      at Object.exports.sign (node_modules/supercop/index.js:142:25)
      at async Context.<anonymous> (test/ShowBufferLimit.js:168:35)

```
This test was run using supercop version 2.2.2 and version 16.4.0 of nodejs on MacOS 11.4

I am not sure what exactly the problem is but if I up the initial limit in the supercop/index.js file for the Memory instance from 2 to say 50000, the problem goes away:
```javascript
async function instantiateModule() {
    if (Module) return;

    const memory  = new WebAssembly.Memory({initial: 2});  // change to 50000?
    const imports = {env:{memory}};
```
I don't know WebAssembly or supercop well enough to attempt any change myself, I suspect the buffer is not being resized properly, so this was just an inefficient work-around.

Thanks for supporting this project!

**Comment by finwo** [comment]
After making [finwo/matter](https://github.com/finwo/matter) actually call `__builtin_wasm_memory_grow` instead of expecting the old behavior of simply allowing the compiled code to access memory without requesting it, the test specific to this seems to indicate this issue is fixed: https://github.com/finwo/supercop/actions/runs/1143852674

Will create a release out of it.
